from asi_meta_layer.code_compiler import CodeCompiler

class ASIMetaLayer:
    def __init__(self):
        self.compiler = CodeCompiler()
        self.active_temp_nodes = []

    def trigger_recompilation(self, crisis_vector):
        print("[ASI Meta-Layer] Chaos detected. Recompiling system topology...")
        temp_code = self.compiler.synthesize_ANI_node(crisis_vector)
        compiled_node = self.compiler.compile(temp_code)
        self.active_temp_nodes.append(compiled_node)
        
        return f"Dynamic Emergency Solution generated by temporary node: {compiled_node}"
